---
settings:
  prefix: '[PerfLog]'
  # MB/s
  io_read: 300
  io_write: 10
  # GHz
  cpu: 2.5
tasks:
  # load
  - id: l1
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'loadFilterBuffer'
    pattern: 'RowBlockDS loadFilterBuffer'
    mode: 'DEFAULT'
    threshold:
      - &IOR
        typ: 'IO_R'
        percent: 1
        warn: 500
        error: 1000
  - id: l2
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'blockIsPassedByFilter'
    pattern: 'RowBlockDS blockIsPassedByFilter'
    mode: 'MUTE'
    threshold:
      - &CPU
        typ: 'CPU'
        percent: 1
        warn: 5
        error: 10
  - id: l3
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'loadColumnBlocks'
    pattern: 'RowBlockDS loadColumnBlocks'
    mode: 'MUTE'
    threshold: [*CPU]
  - id: l4
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.ColumnBlockDS'
    method: 'loadRowsIndex'
    pattern: 'ColumnBlockDS loadRowsIndex'
    mode: 'MUTE'
    threshold: [*CPU]
  - id: l5
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSColumnIterator'
    method: 'next'
    pattern: 'RowBlockDSColumnIterator next'
    mode: 'DEFAULT'
    threshold: [*IOR]
  - id: l6
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'getBlockBitSet'
    pattern: 'RowBlockDS getBlockBitSet'
    mode: 'DEFAULT'
    threshold: [*IOR]
  - id: l7
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSStatisticsColumnIterator'
    method: 'next'
    pattern: 'RowBlockDSStatisticsColumnIterator next'
    mode: 'DEFAULT'
    threshold: [*IOR]
  - id: l8
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSIterator'
    method: 'next'
    pattern: 'RowBlockDSIterator next'
    mode: 'DEFAULT'
    threshold: [*IOR]
  - id: l9
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSStatisticsIterator'
    method: 'next'
    pattern: 'RowBlockDSStatisticsIterator next'
    mode: 'DEFAULT'
    threshold: [*IOR]
  # put
  - id: p1
    clazz: 'io.transwarp.holodesk.storage.ds.segment.Segment'
    method: 'init'
    pattern: 'Segment init'
    mode: 'DEFAULT'
    threshold:
      - &IOW
        typ: 'IO_W'
        percent: 1
        warn: 5
        error: 10
  - id: p2
    clazz: 'io.transwarp.holodesk.storage.ds.segment.WritableAppendOnlySegment'
    method: 'close'
    pattern: 'WritableAppendOnlySegment close'
    mode: 'DEFAULT'
    threshold: [*IOW]
  - id: p3
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'spill'
    pattern: 'RowBlock spill'
    mode: 'DEFAULT'
    threshold: [*IOW]
  - id: p4
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'spillMetaData'
    pattern: 'RowBlock spillMetaData'
    mode: 'DEFAULT'
    threshold: [*IOW]
