---
settings:
  logger_enable: true
  watcher_enable: true
  prefix: '[PerfLog]'
  # MB/s
  io_read: 300
  io_write: 10
  # GHz
  cpu: 2.5

tasks:
  # Default threshold
  - id: threshold
    clazz: 'threshold'
    method: 'default'
    threshold:
      - &IOR
        typ: IO_R
        percent: 1
        warn: 500
        error: 1000
      - &IOW
        typ: IO_W
        percent: 1
        warn: 5
        error: 10
      - &CPU
        typ: CPU
        percent: 1
        warn: 500000
        error: 1000000

  - id: s1
    clazz: 'io.transwarp.holodesk.storage.ds.segment.Segment.InternalRowIterator'
    method: 'init'
    pattern: 'InternalRowIterator init'
    mode: FORCE
    threshold: [*CPU]
    sub_tasks: [ws1]

  - id: ws1
    clazz: 'io.transwarp.holodesk.storage.ds.segment.WritableAppendOnlySegment'
    method: 'load'
    pattern: 'WritableAppendOnlySegment load'
    mode: FORCE
    threshold: [*CPU]
    sub_tasks: [r1]

  # RowBlockDS
  - id: r1
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'load'
    pattern: 'RowBlockDS load'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [r2, r3, r4]
  - id: r2
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'loadFilterBuffer'
    pattern: 'RowBlockDS loadFilterBuffer'
    # mode: FORCE
    threshold: [*IOR]
  - id: r3
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'blockIsPassedByFilter'
    pattern: 'RowBlockDS blockIsPassedByFilter'
    # mode: FORCE
    threshold: [*CPU]
  - id: r4
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'loadColumnBlocks'
    pattern: 'RowBlockDS loadColumnBlocks'
    # mode: FORCE
    threshold: [*CPU]
  - id: r5
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
    method: 'getBlockBitSet'
    pattern: 'RowBlockDS getBlockBitSet'
    # mode: FORCE
    threshold: [*IOR]

  - id: si1
    clazz: 'io.transwarp.holodesk.storage.ds.segment.Segment.InternalRowIterator'
    method: 'iterator'
    pattern: 'InternalRowIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [r1, rbi1, rbi2, rbi3, rbi4]

  # RowBlock Iterator
  - id: rbi1
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSColumnIterator'
    method: 'iterator'
    pattern: 'RowBlockDSColumnIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [cb1, cb2, cb3, cb4]
  - id: rbi2
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSStatisticsColumnIterator'
    method: 'iterator'
    pattern: 'RowBlockDSStatisticsColumnIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [cb1, cb2, cb3, cb4]
  - id: rbi3
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSIterator'
    method: 'iterator'
    pattern: 'RowBlockDSIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [cb1, cb2, cb3, cb4]
  - id: rbi4
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSStatisticsIterator'
    method: 'iterator'
    pattern: 'RowBlockDSStatisticsIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [cb1, cb2, cb3, cb4]
  - id: rbi5
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.GlobalIndexGroupByIterator'
    method: 'iterator'
    pattern: 'GlobalIndexGroupByIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [rbi3, rbi4]
  - id: rbi6
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDSFilterIterator'
    method: 'iterator'
    pattern: 'RowBlockDSFilterIterator iterator'
    mode: FORCE
    threshold: [*IOR]
    sub_tasks: [rbi3]

  # ColumnBlockDS
  - id: cb1
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.HashDictionaryColumnBlockDS'
    method: 'get'
    pattern: 'HashDictionaryColumnBlockDS get'
    # mode: FORCE
    threshold: [*IOR]
  - id: cb2
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.HashDictionaryColumnBlockDS'
    method: 'getBatch'
    pattern: 'HashDictionaryColumnBlockDS getBatch'
    # mode: FORCE
    threshold: [*IOR]
  - id: cb3
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RadixTrieColumnBlockDS'
    method: 'get'
    pattern: 'RadixTrieColumnBlockDS get'
    # mode: FORCE
    threshold: [*IOR]
  - id: cb4
    clazz: 'io.transwarp.holodesk.storage.ds.column.block.RadixTrieColumnBlockDS'
    method: 'getBatch'
    pattern: 'RadixTrieColumnBlockDS getBatch'
    # mode: FORCE
    threshold: [*IOR]

  # put
  # - id: p1
  #   clazz: 'io.transwarp.holodesk.storage.ds.segment.WritableAppendOnlySegment'
  #   method: 'close'
  #   pattern: 'WritableAppendOnlySegment close'
  #   threshold: [*IOW]
  # - id: p2
  #   clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
  #   method: 'spill'
  #   pattern: 'RowBlock spill'
  #   threshold: [*IOW]
  # - id: p3
  #   clazz: 'io.transwarp.holodesk.storage.ds.column.block.RowBlockDS'
  #   method: 'spillMetaData'
  #   pattern: 'RowBlock spillMetaData'
  #   threshold: [*IOW]
